### PR TITLE
Feature: progress tracking

### PR DESCRIPTION
**Pull request by zshannon**
Wanted to add very simple syntax for reporting progress. I haven't written tests yet, but I can if you like this feature and its API. Let me know if this looks like something that could eventually be merged into master.

### CODE REVIEW

**Comment by Thomvis** [comment]
Hi and thanks for the PR! Unfortunately, progress reporting is not something that I'd like to see in BrightFutures.

A while ago I was tempted to add this feature to BrightFutures (and also cancellation and pausing), but decided it would be better to keep BrightFutures simple. Instead, I started [GoodProgress](https://github.com/Thomvis/GoodProgress), which is still in its early stages, and eventually want to create something that combines progress and future into a single thing (a [task](https://github.com/ReactKit/SwiftTask), perhaps?)

If you want, please give GoodProgress a try. I'd be happy to discuss any suggestions and improvements you have for that.

See also https://github.com/Thomvis/BrightFutures/issues/17.

**Comment by epologee** [comment]
Hi @Thomvis, has your opinion on this changed, regarding that GoodProgress has become somewhat stale by now?

My reason for asking: I'm now mixing a custom progress implementation (way less advanced than NSProgress) with BrightFuture promises/futures. In my implementation, I'm calling `promise.failure(_:)` and `promise.success(_:)` left and right, yet would really appreciate calling `promise.progress(_:)` instead of breaking out to a stored callback in the wrapping type.

**Comment by Thomvis** [comment]
Thanks for your kind words! GoodProgress is indeed pretty stale and I don't think that is going to change anytime soon.

I still think that the Future type should not have anything to do with progress. This doesn't mean that you can't make a nice *new* type that combines the powers of Futures with some kind of progress reporting.

You could look into creating a new type that wraps a Future. The wrapping type should also conform to AsyncType so you can use it as a regular Future. (Most of a future's code lives in protocol extensions on AsyncType.) In addition to the future it wraps, this new type also keeps a reference to progress callbacks. You'd be able to use the `ExecutionContext` system as well. Does that make sense?

**Comment by epologee** [comment]
That sounds like an interesting idea. Would you be willing to review incoming pull requests, changing small bits to allow for a "wrapper module" to access certain internals of BrightFutures? For example, publicizing the `var DefaultThreadingModel` or `func defaultContext() -> ExecutionContext`?

**Pull request closed without merging**
