### PR TITLE
Add Swift 2 / Xcode 7 support

### PR DESCRIPTION
**Pull request by Thomvis**
Open questions:

- `future.success(value)`, `future.failure(error)` etc. are now throwing. While I think that in theory this is a good approach, in practice I find it a bit annoying and its making me add a lot of `try!`'s. Consider making `future.success(value)` non-throwing and create a second one (e.g. `future.firstAndOnlySuccess(value)`) that throws.

### CODE REVIEW

**Comment by Thomvis** [comment]
I've reverted the behavior of `f.success` etc. back to the BrightFutures 2.0 approach: an assert will be triggered if an already completed future is completed again. I experimented with having it throw an error but in practice this would make me add a lot of `try!`'s. Also, since this is considered a programmer error, a recoverable error would not be the best fit. I also considered making it a fatalError, but I don't want that to happen for people in production. Feedback is welcome!

**Comment by Mistobaan** [comment]
What is the status of this PR ?

**Comment by Thomvis** [comment]
The current beta (beta 4) works great and we're actually shipping with it at work. I just need to find some time to wrap op the release (documentation etc.). I've also been delaying the release a bit in order to get feedback from users before making it final, but that didn't really happen so I should probably just go ahead with it.

**Comment by JoshSmith** [comment]
So looks like you're going to go ahead with this? Anxiously awaiting it as a dependent project really needs the Swift 2.0 support!

Good work on the upgrade. :+1:

**Comment by kurko** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Pull request merged**
