### PR TITLE
Swift 5

### LINKED ISSUE #205: Support Swift 5

### PR DESCRIPTION
**Pull request by kimdv**
Hi! 

I started porting to Swift 5 with the new Swift Result and it resolves #205 

Had some problems with the generics in Swift, so needed to copy the some classes from the old Result framework. 

It would be nice if we somehow can remove those. 

Thanks! 🚀

### CODE REVIEW

**Comment by phimage** [comment]
- Carfile and Cartfile.resolved could be removed 
- Package.swift could be edited

**Comment by Thomvis** [comment]
Thanks for the PR. I'll have a look at it tomorrow.

**Comment by mathebox** [comment]
I think `NoError` can also be replaced by `Never`.
Alternatively, you could define a typealias to avoid breaking changes.

https://github.com/apple/swift-evolution/blob/master/proposals/0215-conform-never-to-hashable-and-equatable.md

**Comment by Thomvis** [comment]
I've been adding some changes on top of this PR, which can be found here: https://github.com/Thomvis/BrightFutures/tree/kimdv-kimdv/swift-5.

@mathebox I agree with your suggestion to use `Never`. Breaking changes are fine by me.

I think `ResultProtocol` is still needed, so we can keep that.

**Comment by kimdv** [comment]
Rebased on solved conflicts

**Comment by Thomvis** [comment]
Thanks! A few comments:
- Can you revert the @testable imports back to regular imports? Regular imports are stricter and should suffice.
- CI is failing, I think you at least need to update the travis configuration to use the 12.2 simulators
- Can you make sure the Swift 5 migrator has run for all framework & test targets (this should also update the Swift language version to 5 for all targets)

**Comment by Thomvis** [comment]
Thanks for your work! I think this could be released as a first beta of 8.0. 

There's one thing I'm trying to figure out: can we make this work without adding new public API to the Result type. Users of BrightFutures will now, for example, all have a `result` property on their Result instances. I think that's suboptimal. Not sure if we can circumvent this. Any ideas? If not, we should probably move ahead and create a release.

**Comment by kimdv** [comment]
So you think we should make `ResultProtocol` internal? 

I don't think it is possible because it is used on other public API's

**Comment by Thomvis** [comment]
Since https://github.com/ReactiveCocoa/ReactiveSwift/pull/702 is doing something very similar to what we're doing, I believe we're good and I'll move forward with the release.

**Comment by Thomvis** [comment]
Thanks again for your work. 8.0.0 has been released! 🚀 

I've invited you as a collaborator if you wish to contribute in the future.

**Comment by kimdv** [comment]
Thanks a lot @Thomvis ! I have accepted 🚀

**Pull request merged**
