### PR TITLE
Swift 2.2/Xcode 7.3

### PR DESCRIPTION
**Pull request by Noobish1**
I believe this is all the necessary changes for Swift 2.2/Xcode 7.3.

### CODE REVIEW

**Comment by Thomvis** [comment]
Thanks so much for the PR. Looks good. A few questions/remarks:

- The version number should be 4.0.0, because the upgrade to Result 2 (with their NoError type) is breaking
- I think it'd be good to release it as a beta 1, because it seems Result 2.0.0 was supposed to be a pre-release (https://github.com/antitypical/Result/pull/147)
- This release would not support Swift 2.1, right, because of the `associatedtype`. Not an issue, because the 3.x version is stable and people will probably migrate to Swift 2.2 soon anyway.

If you agree, can you update your PR accordingly? Thanks again!

**Comment by Noobish1** [comment]
Your comments are totally valid, i've bumped the podspec to 4.0.0-beta.1.

**Comment by Noobish1** [comment]
Btw, i'm not sure what you wanted to do with this:
```
extension NoError: Equatable { }
  		  
public func ==(lhs: NoError, rhs: NoError) -> Bool {
    return true
}
```

**Comment by pshc** [comment]
_If a type `T` in the forest has no values, is `T: Equatable` sound?_

**Comment by Thomvis** [comment]
Hmm, that code looks strange indeed. I'm not sure, but I might have written it to be able to implement equals for `BrightFuturesError<NoError>`. I think there are some tests that depend on being able to compare errors of that type.

**Comment by Noobish1** [comment]
yea that's where it's used.

**Comment by Thomvis** [comment]
I think what we should do is have another overload of == that accepts two `BrightFuturesErrors<NoError>`s.

**Comment by Noobish1** [comment]
Makes sense to me.

**Comment by Noobish1** [comment]
I've removed the NoError extension and == overload and added an == overload for two BrightFuturesError<NoError> operands as requested.

**Comment by Thomvis** [comment]
Sorry for not replying sooner. I think the implementation of the `==` overload should be different. Right now it would mean that `.NoSuchElement` is equal to `InvalidationTokenInvalidated `. I think it should look like this:

```swift
/// Returns `true` if `left` and `right` are both of the same case ignoring .External associated value
public func ==(lhs: BrightFuturesError<NoError>, rhs: BrightFuturesError<NoError>) -> Bool {
    switch (lhs, rhs) {
    case (.NoSuchElement, .NoSuchElement): return true
    case (.InvalidationTokenInvalidated, .InvalidationTokenInvalidated): return true
    case (.External(let lhs), .External(let rhs)): return true // this cannot happen because NoError cannot be instantiated
    default: return false 
    }
}
```

Can you fix this. After that, the PR is ready for merging. Thanks again!

**Comment by Noobish1** [comment]
That makes sense, done.

**Comment by Thomvis** [comment]
Thanks so much, merged it in!

**Pull request merged**
